export const refList = [
	{
		league: 'Ektraliga kobiet',
		referees: [
			{ surname: 'Płaskocińska', name: 'Agnieszka' },
			{ surname: 'Kupidura', name: 'Katarzyna' },
		],
	},
	{
		league: 'III liga',
		referees: [
			{ surname: 'Chrząstek', name: 'Norbert' },
			{ surname: 'Muc', name: 'Dawid' },
		],
	},
	{
		league: 'IV liga',
		referees: [
			{ surname: 'Jabłoński', name: 'Jakub' },
			{ surname: 'Maciejewski', name: 'Grzegorz' },
			{ surname: 'Pawluk', name: 'Jan' },
			{ surname: 'Pawłowicz', name: 'Filip' },
			{ surname: 'Janik', name: 'Wojciech' },
			{ surname: 'Kapusta', name: 'Piotr' },
			{ surname: 'Kupidura', name: 'Michał' },
		],
	},
	{
		league: 'V liga',
		referees: [
			{ surname: 'Kupidura', name: 'Łukasz' },
			{ surname: 'Majewski', name: 'Jakub' },
			{ surname: 'Gałużny', name: 'Mateusz' },
			{ surname: 'Połosa', name: 'Milena' },
		],
	},
	{
		league: 'Liga okręgowa',
		referees: [
			{ surname: 'Dobrasiewicz', name: 'Szymon' },
			{ surname: 'Figarski', name: 'Tomasz' },
			{ surname: 'Elertowicz', name: 'Patryk' },
			{ surname: 'Głowacki', name: 'Daniel' },
			{ surname: 'Gromek', name: 'Jarosław' },
			{ surname: 'Hawajski', name: 'Artur' },
			{ surname: 'Ksyta', name: 'Tomasz' },
			{ surname: 'Łyżwiński', name: 'Mariusz' },
			{ surname: 'Maciejewski', name: 'Daniel' },
			{ surname: 'Molenda', name: 'Michał' },
			{ surname: 'Rojek', name: 'Patryk' },
			{ surname: 'Sochaj', name: 'Marcin' },
			{ surname: 'Wrochna', name: 'Michał' },
			{ surname: 'Banaczek', name: 'Kacper' },
			{ surname: 'Sambor', name: 'Jakub' },
			{ surname: 'Siewierski', name: 'Jakub' },
		],
	},
	{
		league: 'Klasa A',
		referees: [
			{ surname: 'Banasik', name: 'Kacper' },
			{ surname: 'Brzeski', name: 'Dawid' },
			{ surname: 'Czarnota', name: 'Paweł' },
			{ surname: 'Dobrasiewicz', name: 'Damian' },
			{ surname: 'Erbel', name: 'Paulina' },
			{ surname: 'Gromek', name: 'Norbert' },
			{ surname: 'Janas', name: 'Bartłomiej' },
			{ surname: 'Kosiński', name: 'Marcin' },
			{ surname: 'Fereniec', name: 'Kacper' },
			{ surname: 'Suwała', name: 'Łukasz' },
			{ surname: 'Wajs', name: 'Michał' },
			{ surname: 'Gajda', name: 'Piotr' },
			{ surname: 'Malmur', name: 'Pawet' },
			{ surname: 'Moskwa  ', name: 'Kacper' },
			{ surname: 'Paduch', name: 'Mateusz' },
		],
	},
	{
		league: 'Klasa B',
		referees: [
			{ surname: 'Metlerski', name: 'Piotr' },
			{ surname: 'Ciecierski', name: 'Krzysztof' },
			{ surname: 'Pawluczuk', name: 'Szymon' },
			{ surname: 'Pluta', name: 'Krzysztof' },
			{ surname: 'Sieczka', name: 'Tomasz' },
			{ surname: 'Kupidura', name: 'Weronika' },
			{ surname: 'Mazurkiewicz', name: 'Miłosz' },
			{ surname: 'Lenart', name: 'Mikołaj' },
			{ surname: 'Pokorski', name: 'Marcin' },
			{ surname: 'Pomagalski', name: 'Rafał' },
			{ surname: 'Wojtowicz', name: 'Mateusz' },
			{ surname: 'Figura', name: 'Szymon' },
			{ surname: 'Kuflikowski', name: 'Michał' },
			{ surname: 'Fijałkowski', name: 'Jakub' },
			{ surname: 'Dziubiński', name: 'Adrian' },
			{ surname: 'Róg', name: 'Jakub' },
			{ surname: 'Tramś', name: 'Sebastian' },
			{ surname: 'Zanjat', name: 'Mateusz' },
			{ surname: 'Pawlak ', name: 'Przemysław' },
		],
	},
	{
		league: 'Asystenci okręgowi',
		referees: [
			{ surname: 'Brzeski', name: 'Łukasz' },
			{ surname: 'Jeżak', name: 'Dawid' },
			{ surname: 'Karcz', name: 'Jakub' },
			{ surname: 'Łukasiewicz', name: 'Maria' },
			{ surname: 'Dolega', name: 'Kacper' },
			{ surname: 'Posuniak', name: 'Michał' },
			{ surname: 'Dobrowolska', name: 'Aleksandra' },
			{ surname: 'Posuniak', name: 'Maciej' },
			{ surname: 'Piątek', name: 'Kamil' },
		],
	},
	{
		league: 'Klasa S',
		referees: [
			{ surname: 'Aleksandrowicz', name: 'Łukasz' },
			{ surname: 'Badowski', name: 'Artur' },
			{ surname: 'Birkowski', name: 'Dariusz' },
			{ surname: 'Dujko', name: 'Adam' },
			{ surname: 'Dziubiński', name: 'Tomasz' },
			{ surname: 'Fereniec', name: 'Jarosław' },
			{ surname: 'Gałecki', name: 'Józef' },
			{ surname: 'Gierczak', name: 'Sławomir' },
			{ surname: 'Jakubowski', name: 'Wojciech' },
			{ surname: 'Jastrzębski', name: 'Ireneusz' },
			{ surname: 'Kiljanek', name: 'Rafał' },
			{ surname: 'Krajewski', name: 'Michał' },
			{ surname: 'Lubecki', name: 'Adam' },
			{ surname: 'Łukasiewicz', name: 'Paweł' },
			{ surname: 'Marus ', name: 'Jacek ' },
			{ surname: 'Mortka', name: 'Zbigniew' },
			{ surname: 'Pawlak', name: 'Artur' },
			{ surname: 'Piątek', name: 'Artur' },
			{ surname: 'Posuniak', name: 'Tomasz' },
			{ surname: 'Prokop', name: 'Piotr' },
			{ surname: 'Puton', name: 'Jarosław' },
			{ surname: 'Rafalik', name: 'Tomasz' },
			{ surname: 'Rojek', name: 'Grzegorz' },
			{ surname: 'Smoliński', name: 'Tomasz' },
			{ surname: 'Sobania', name: 'Daniel' },
			{ surname: 'Stani', name: 'Tomasz' },
			{ surname: 'Stanios', name: 'Tadeusz' },
			{ surname: 'Strzelec', name: 'Michał' },
			{ surname: 'Szewczyk', name: 'Rafał' },
			{ surname: 'Warchoł', name: 'Artur' },
			{ surname: 'Wierzbicki', name: 'Michał' },
			{ surname: 'Więczasek', name: 'Rafał' },
			{ surname: 'Wnuk', name: 'Dariusz' },
			{ surname: 'Wrochna', name: 'Łukasz' },
			{ surname: 'Zelga', name: 'Jacek' },
		],
	},
	{
		league: 'Obserwatorzy',
		referees: [
			{ surname: 'Borkowski', name: 'Mariusz' },
			{ surname: 'Cholewa', name: 'Dariusz' },
			{ surname: 'Pipczyński', name: 'Sławomir' },
			{ surname: 'Zając', name: 'Anna' },
			{ surname: 'Aleksandrowicz', name: 'Łukasz' },
			{ surname: 'Smoliński', name: 'Tomasz' },
			{ surname: 'Puton', name: 'Jarosław' },
		],
	},
	{
		league: 'Klasa P',
		referees: [{ surname: 'Guz', name: 'Luiza' }],
	},
	{
		league: 'Kurs 2024',
		referees: [
			{ surname: 'Farbiś', name: 'Michał' },
			{ surname: 'Jabłoński', name: 'Kacper' },
			{ surname: 'Rdzanek', name: 'Michał' },
			{ surname: 'Skrzypek', name: 'Stanisław' },
			{ surname: 'Suligowski', name: 'Bartosz' },
		],
	},
]

function sortRefereesBySurname(leaguesArray) {
	leaguesArray.forEach(league => {
		league.referees.sort((a, b) => a.surname.localeCompare(b.surname))
	})
	return leaguesArray
}

const sortedRefListData = sortRefereesBySurname(refList)

export default sortedRefListData
